### PR TITLE
feat: parse certificates, entitlements, symbol table for Mach-O

### PR DESCRIPTION
**Pull request by latonis**
Implementing another load command for Mach-O. here soon we'll have the ground work to parse the entire symbol table and info :smile_cat: 
- Implemented tests, LC_SYMTAB, LC_DYLD_INFO(_ONLY), and more which is needed to parse symbol tables
- Implemented certificate parsing for signed binaries

### CODE REVIEW

**Comment by latonis** [comment]
@plusvic / @TommYDeeee , thoughts on adding something like https://www.anomali.com/blog/symhash for the Mach-O module as we now parse symtable strings with this PR? Mac version of ImpHash 😸

**Comment by latonis** [comment]
Looks like the tests failed due to a Heroku CDN issue, will push another commit later to get tests to run again

**Comment by plusvic** [comment]
Before the `macho` module keeps growing I would like to merge this refactoring: https://github.com/VirusTotal/yara-x/pull/76

**Comment by latonis** [comment]
> Before the `macho` module keeps growing I would like to merge this refactoring: #76

will hold off on any other progress for the module until #76 is merged 😸

**Comment by latonis** [comment]
Moving the new work to #78 as I did not want to rebase and all that jazz, so re-implementing from fresh branch

**Comment by latonis** [comment]
Only thing left to port is the entitlement present function and then this can be closed as everything was rolled into #78

**Comment by latonis** [comment]
Everything has been refactored and reimplemented in #78. Closing this in favor of that one being reviewed and merged. 😸

**Pull request closed without merging**
