### PR TITLE
feat(go): expose rule's metadata in Go API

### PR DESCRIPTION
**Pull request by codedninja**
Reference issue: #120 & #118

### CODE REVIEW

**Comment by plusvic** [comment]
Now that I see an implementation I'm reconsidering the use of JSON as a format for exchanging metadata information. There are some issues with JSON that make it far from ideal:

* We lose information about whether a number is actually a float or an integer.
* For non-UTF8 strings we are going to get an array of numbers, which will be translated to `[]float` instead of `[]byte`.

**Comment by codedninja** [comment]
When I wrote the tests I noticed that as well, maybe a similar implementation as the original Yara did? Which is what I was originally aiming for when attempting to implement it in the C-API.

```C
struct YR_META
{
  DECLARE_REFERENCE(const char*, identifier);
  DECLARE_REFERENCE(const char*, string);

  int64_t integer;
  int32_t type;
  int32_t flags;
};
```

**Comment by plusvic** [comment]
I've refactored the C API for obtaining the rule's metadata. See: 9f90eaab37a764cc90c40881fc60e448483bb7bf

**Comment by codedninja** [comment]
There is a slight error with the `float` variant inside of the `YRX_METADATA_VALUE` union. When the header file gets generated it makes it into "two or more data types in declared specifier" due to `float` being a reserved keyword.

While you decide on the new name for the float variant, I shall temporary rename to get the go package working.

**Comment by plusvic** [comment]
> There is a slight error with the `float` variant inside of the `YRX_METADATA_VALUE` union. When the header file gets generated it makes it into "two or more data types in declared specifier" due to `float` being a reserved keyword.
> 
> While you decide on the new name for the float variant, I shall temporary rename to get the go package working.

Fixed in 497c678cb288dbfdfc12415741e301d724735c97

**Pull request merged**
