### PR TITLE
feat: mach-o parsing for LC_RPATH cmds

### PR DESCRIPTION
**Pull request by latonis**
Implement parsing for LC_RPATH commands for dynamic linking

- test file for macho updated to include an rpath load command
- organized the consts more clearly for dynamically linked constants

### CODE REVIEW

**Comment by latonis** [comment]
@plusvic, whenever you have time, I was going to go ahead and do PRs for each type of load command for parsing for mach-o, but would you prefer one large PR of numerous load command parsing instead? I can do whatever is easier, just figured this would be a good started :)

**Comment by plusvic** [comment]
> @plusvic, whenever you have time, I was going to go ahead and do PRs for each type of load command for parsing for mach-o, but would you prefer one large PR of numerous load command parsing instead? I can do whatever is easier, just figured this would be a good started :)

I prefer multiple smaller PRs than a single larger one.

**Comment by latonis** [comment]
Ah ok wonderful. Thanks @plusvic!

I'll do that format for each load command in the mach-o parsing, thanks 😸

**Review by plusvic — APPROVED** [review]

**Comment by latonis** [comment]
Merge conflict has been fixed 🙂

**Pull request merged**
